### ISSUE TITLE
Cannot scan in Bank app

### ISSUE THREAD

**Issue by kamontat** [dtinth/promptpay-qr#12]
When we use the qrcode in bank application (e.g. KBank, SCB), the telephone number will be wrong by the prefix of them.

**Comment by dtinth** [comment]
@kamontat Thanks for the report. Can you give a specific example?

- What is the phone number you try to use?
- What is the generated QR code?
- After scanning, what is the actual result?
- What is the expected result?

Thanks

**Comment by kamontat** [comment]
I use this app via website in iOS

1. First I use phone number like 08x-xxx-xxxx 
2. And then it’s will auto generate qrcode 
3. After I use Kbank app, the result show the prefix as `00608xxxxx`

**Comment by kamontat** [comment]
After I try to delete my phone number and try to add again, the issues gone away. I think this issue cause by different of app version. Sorry about that.

**Comment by dtinth** [comment]
Closing as resolved.
