### ISSUE TITLE
[Question] E-Wallet id and Tax id target length

### ISSUE THREAD

**Issue by tspn** [dtinth/promptpay-qr#19]
Regarding the length of both type of target e-wallet and tax id,
I haven't read any e-wallet and tax id specification yet, but I wonder why e-wallet length must >= 15 and tax-id must be >= 13. Do we have any 14 digit tax-id  ?

Thanks!
https://github.com/dtinth/promptpay-qr/blob/0bb43fd254c4167fbb00ea7e6843304cc69971b9/index.js#L39

**Comment by dtinth** [comment]
Hello and thanks for the question. No, I have not seen any Tax ID of length 14, but I was not sure what should happen when encountered with a string of length 14...

At that time I did not think about error cases, and so did not make the library able to throw errors on malformed input. That is why it was implemented this way.

**Comment by dtinth** [comment]
By the way, there is a standard document for Thailand QR Payment here, I discovered last month:

https://www.bot.or.th/Thai/PaymentSystems/StandardPS/Documents/ThaiQRCode_Payment_Standard.pdf

- **Mobile number** is in form of `0066xxxxxxxxx` so replacing `0066` with `0` results in an ID of length 10.
- **National ID** and **Tax ID** has length 13.
- **E-wallet ID** has length 15.
- Only **Bank account** has a variable length. But it is reserved for future and not in use today...

**Comment by tspn** [comment]
Understood, Thanks!
